//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSendMessage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMessage
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public System.DateTime Date { get; set; }
        public string Confirmation { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
